### ISSUE TITLE
Update .NET Rocks to master feed

### ISSUE THREAD

**Issue by bothzoli** [codingblocks/qit-podcast-feed-loader#7]
## 👣 Steps to reproduce

Only the latest 20 episodes are indexed because we are not using the podcast's master feed.
(moving [issue 247](https://github.com/codingblocks/qit.cloud/issues/247) from qit.cloud)

## 🔬 Expected behavior

All 1594 episodes should be indexed.

## 🛠️ Recommended fix

Update QIT for .NET Rocks to the following feed:

- http://www.pwop.com/feed.aspx?show=dotnetrocks&filetype=master

**Comment by THEjoezack** [comment]
I'm working on converting QIT over to use Elasticsearch, and then we should have plenty of room for all the episodes!
