### ISSUE TITLE
Adding a podcast?

### ISSUE THREAD

**Issue by mgroves** [codingblocks/qit-podcast-feed-loader#8]
To add a show, shall I just create a PR for feeds.json? I'd like to add three of the shows I participate in, if that's okay with you: Cross Cutting Concerns, DotNetBytes, and The NoSQL Database Podcast.

**Comment by mgroves** [comment]
looks like .NET Bytes was already brought up in issue #5

**Comment by THEjoezack** [comment]
You got it! I have some work to do in there this weekend anyway, so I can it too. Testing is a bit awkward right now but this will soon be fixed :)

**Comment by mgroves** [comment]
Terrific! Here's a feed for Cross Cutting Concerns: http://feeds.feedburner.com/CrossCuttingConcerns

Here's a feed for the NoSQL Database Podcast: http://nosql.libsyn.com/rss

**Comment by THEjoezack** [comment]
Got 'em @mgroves! I did end up using a different feed for CCC though: http://feeds.feedburner.com/CrossCuttingConcernsPodcast

The one you pasted keeps returning 0 episodes for me, castfeedvalidator.com shows the same thing (0 episodes) but I can't see why: http://castfeedvalidator.com/?url=http://feeds.feedburner.com/CrossCuttingConcerns

Here's what it looks like: 
https://qit.cloud/search/%22Cross%20Cutting%20Concerns%22+%7C+%22NoSQL+Database+Podcast%22%20%7C%20%22.NET%20Bytes%22

**Comment by mgroves** [comment]
Thank you for adding. Just a quick note on those two feeds. I think the the one I gave you is the feed for my overall blog, while the one you used is just for the podcast. I messed up but you fixed it for me, thank you! :)
